### PR TITLE
docs: Update contributing guide with authentication setup instructions

### LINKED ISSUE #259: Add auth setup step to the getting started guide in CONTRIBUTING
When setting up the repo for the first time it's necessary to run `npx @convex-dev/auth`. Add a step to the getting started guide instructing users to run this. Link to Convex Auth docs.

### PR DESCRIPTION
**Pull request by belhajManel**
### What changed?
Resolves [#259](https://github.com/namesakefyi/namesake/issues/259) Updated the contributing guide to include authentication setup instructions with Convex, including steps for installing dependencies, generating keys and updating envs.

### Why?
To help contributors easily set up authentication for local development with Convex.

### How was this change made?
I added a new section to the guide with clear steps for setting up authentication, including commands and code examples.

### How was this tested?
The instructions were reviewed against Convex's manual setup guide.

### CODE REVIEW

**Comment by kydecker** [comment]
Hey @belhajManel! Thanks so much for this PR to improve the contribution guide.

I think there's an even simpler step we can add here in place of the manual instructions!

```shell
npx @convex-dev/auth
```

This initialization command will run all of the manual steps without needing to install new packages, generate authentication keys, or set `ENV` variables.

I think it makes sense to _only_ share this command in Namesake's guide, and then link to Convex Auth's [Manual Setup](https://labs.convex.dev/auth/setup/manual) in case someone needs an escape hatch (or is curious about what the command does).

**Comment by belhajManel** [comment]
Indeed @evadecker this is a simpler approach.

I've updated the contribution guide. Let me know if there's anything else you'd like to tweak!

**Comment by kydecker** [comment]
Thanks! What I mean to say is I think we can remove all the numbered steps from the guide. 

The `npx` command will execute the steps automatically, and if anyone runs into trouble, they can click out to the manual installation guide.

**Comment by belhajManel** [comment]
Fixed

**Review by kydecker — APPROVED** [review]
I made some small edits to the text, but LGTM! Thanks for improving the docs, @belhajManel!

**Pull request merged**
